### ISSUE TITLE
Floating point math

### ISSUE THREAD

**Issue by SlyEcho** [pavroto/tntouch#3]
There is a snippet like this in several places:

```c
TEMPLATE_STEP * ceil (bash_result_len / TEMPLATE_STEP)
```

The issue here is that the input to the `ceil()` function is performed using integers and the result is cast to `double` for passing into `ceil()`.
This means the effective operation is effectively:

```c
TEMPLATE_STEP * floor (bash_result_len / TEMPLATE_STEP)
```

Of course, one way is to cast the numbers into floating points first:

```c
TEMPLATE_STEP * ceil ((double)bash_result_len / (double)TEMPLATE_STEP)
```

But I believe a better solution is to avoid floating point operations entirely and to perform a round-up using integer division instead like this or something similar:

```c
(bash_result_len + TEMPLATE_STEP-1) / TEMPLATE_STEP * TEMPLATE_STEP
```

**Comment by pavroto** [comment]
Fixed in bfccc892096b1f7a298981d8a8fe75465b22b470
